In [1]:
import pandas as pd
import re
!pip install gspread gspread_dataframe
import gspread
from gspread_dataframe import set_with_dataframe
from google.colab import auth
from google.auth import default

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

from google.colab import drive
drive.mount('/content/drive')

Requirement already satisfied: gspread in /usr/local/lib/python3.12/dist-packages (6.2.1)
Requirement already satisfied: gspread_dataframe in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from gspread) (2.43.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gspread) (1.2.2)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from gspread_dataframe) (2.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from gspread_dataframe) (1.17.0)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.12.0->gspread) (6.2.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.12.0->gspread) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.12.0->gspread) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->gspread_dataframe) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->gspread_dataframe) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->gspread_dataframe) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->gspread_dataframe) (2025.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.1)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2025.11.12)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
df = pd.read_csv('/content/drive/MyDrive/SEMESTER 5/Pemrosesan Data/UAS PVD/DATA_WISATA.csv')
print("Columns in CSV:", df.columns.tolist())

df.head(6)

Columns in CSV: ['no', 'nama', 'type', 'vote_average', 'vote_count', 'htm_weekday', 'htm_weekend', 'latitude', 'longitude', 'image', 'description']

,no,nama,type,vote_average,vote_count,htm_weekday,htm_weekend,latitude,longitude,image,description
0,9,Candi Borobudur,Budaya_Dan_Sejarah,4.7,81922,50000,50000,-7.607087,110.203623,https://res.cloudinary.com/dfciqrwpe/image/upl...,candi yang pernah masuk sebagai salah satu dar...
1,10,Candi Prambanan,Budaya_Dan_Sejarah,4.7,71751,50000,50000,-7.751835,110.491532,https://res.cloudinary.com/dfciqrwpe/image/upl...,candi prambanan adalah kompleks candi hindu te...
2,24,Tebing Breksi,Alam,4.4,51431,10000,10000,-7.781477,110.504576,https://res.cloudinary.com/dfciqrwpe/image/upl...,tebing breksi merupakan tempat wisata yang ber...
3,343,Gembira Loka Zoo,Buatan,4.5,36337,20000,25000,-7.806234,110.396798,https://res.cloudinary.com/dfciqrwpe/image/upl...,gambira loka adalah kebun binatang yang berada...
4,346,The Palace of Yogyakarta (Keraton Yogyakarta),Budaya_Dan_Sejarah,4.6,30091,8000,8000,-7.805284,110.364203,https://res.cloudinary.com/dfciqrwpe/image/upl...,kompleks keraton merupakan museum yang menyimp...
5,8,Taman Sari,Budaya_Dan_Sejarah,4.6,27899,5000,5000,-7.809833,110.359512,https://res.cloudinary.com/dfciqrwpe/image/upl...,taman sari yogyakarta merupakan salah satu ban...

In [3]:
df.info()
df.describe()
df.isnull().sum()


# print("Columns with repr:", [repr(col) for col in df.columns])

# df.columns = df.columns.str.strip().str.lower()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 476 entries, 0 to 475
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   no            476 non-null    int64
 1   nama          476 non-null    object
 2   type          476 non-null    object
 3   vote_average  476 non-null    float64
 4   vote_count    476 non-null    int64
 5   htm_weekday   476 non-null    int64
 6   htm_weekend   476 non-null    int64
 7   latitude      476 non-null    float64
 8   longitude     476 non-null    float64
 9   image         476 non-null    object
 10  description   476 non-null    object
dtypes: float64(3), int64(4), object(4)
memory usage: 41.0+ KB

no              0
nama            0
type            0
vote_average    0
vote_count      0
htm_weekday     0
htm_weekend     0
latitude        0
longitude       0
image           0
description     0
dtype: int64

In [4]:
print("Jumlah data duplikat :", df.duplicated().sum())

print("Hasil statistik dasar:\n",df.describe())

Jumlah data duplikat : 0
Hasil statistik dasar:
               no  vote_average    vote_count   htm_weekday   htm_weekend  \
count  476.00000    476.000000    476.000000  4.760000e+02  4.760000e+02
mean   252.64916      4.445588   1856.436975  1.949475e+04  2.139496e+04
std    146.79256      0.400055   6561.024537  7.973854e+04  8.679566e+04
min      1.00000      1.000000      1.000000  0.000000e+00  0.000000e+00
25%    125.75000      4.300000     11.000000  0.000000e+00  0.000000e+00
50%    252.50000      4.500000    143.500000  5.000000e+03  5.000000e+03
75%    379.25000      4.600000    940.250000  1.200000e+04  1.500000e+04
max    510.00000      5.000000  81922.000000  1.380000e+06  1.380000e+06

         latitude   longitude
count  476.000000  476.000000
mean    -7.822843  110.396433
std      0.139531    0.121634
min     -8.200347  109.913062
25%     -7.878042  110.354135
50%     -7.805627  110.398674
75%     -7.748537  110.468887
max     -7.565783  110.710377

In [5]:
df['htm_weekday'] = df['htm_weekday'].fillna(df['htm_weekday'].median())
df['htm_weekend'] = df['htm_weekend'].fillna(df['htm_weekend'].median())
df['description'] = df['description'].fillna('')
df.isnull().sum()

no              0
nama            0
type            0
vote_average    0
vote_count      0
htm_weekday     0
htm_weekend     0
latitude        0
longitude       0
image           0
description     0
dtype: int64

In [6]:
indonesian_stopwords = ["yang", "di", "dan", "adalah", "ini", "itu", "untuk", "dengan", "pada", "ke", "dari"]
def clean_text(text):
    if not isinstance(text, str): return ""
    text = text.lower() # Kecilkan huruf
    text = re.sub(r'[^a-z\s]', '', text) # Hapus angka dan simbol
    words = text.split()
    words = [w for w in words if w not in indonesian_stopwords and len(w) > 1]
    return " ".join(words)

df['description_clean'] = df['description'].apply(clean_text)
df_clean = df.copy()
df_clean.head()
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 476 entries, 0 to 475
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   no                 476 non-null    int64
 1   nama               476 non-null    object
 2   type               476 non-null    object
 3   vote_average       476 non-null    float64
 4   vote_count         476 non-null    int64
 5   htm_weekday        476 non-null    int64
 6   htm_weekend        476 non-null    int64
 7   latitude           476 non-null    float64
 8   longitude          476 non-null    float64
 9   image              476 non-null    object
 10  description        476 non-null    object
 11  description_clean  476 non-null    object
dtypes: float64(3), int64(4), object(5)
memory usage: 44.8+ KB

In [7]:
def kategori_harga(x):
    if x < 10000:
        return "Murah"
    elif x <= 50000:
        return "Menengah"
    else:
        return "Mahal"

df_clean['kategori_harga_weekday'] = df_clean['htm_weekday'].apply(kategori_harga)
df_clean['kategori_harga_weekend'] = df_clean['htm_weekend'].apply(kategori_harga)

In [8]:
def rating_segment(x):
    if x >= 4.5:
        return "Sangat Baik"
    elif x >= 4:
        return "Baik"
    elif x >= 3:
        return "Cukup"
    else:
        return "Perlu Perbaikan"

df_clean['rating_segment'] = df_clean['vote_average'].apply(rating_segment)

In [9]:
df_clean.to_excel("DATA_WISATA_PREPROCESSED.xlsx", index=False)

In [10]:
df_clean[['htm_weekday', 'kategori_harga_weekday',
          'htm_weekend', 'kategori_harga_weekend',
          'vote_average', 'rating_segment']].head()

,htm_weekday,kategori_harga_weekday,htm_weekend,kategori_harga_weekend,vote_average,rating_segment
0,50000,Menengah,50000,Menengah,4.7,Sangat Baik
1,50000,Menengah,50000,Menengah,4.7,Sangat Baik
2,10000,Menengah,10000,Menengah,4.4,Baik
3,20000,Menengah,25000,Menengah,4.5,Sangat Baik
4,8000,Murah,8000,Murah,4.6,Sangat Baik

In [11]:
df_clean['kategori_harga_weekday'].value_counts()
df_clean['rating_segment'].value_counts()

rating_segment
Sangat Baik        242
Baik               213
Cukup               18
Perlu Perbaikan      3
Name: count, dtype: int64

In [12]:
spreadsheet = gc.create("DATA_WISATA_PREPROCESSED")
worksheet = spreadsheet.sheet1
set_with_dataframe(worksheet, df_clean)